package cg41;

import java.sql.SQLException;
import javax.swing.WindowConstants;

public class AddCourse extends javax.swing.JFrame {

    boolean myLocalError = false;
    String myLocalString = "";
    String catSelect, errorMessage = "";
    int thisError = 0;
    int numRecords = 0;
    int i = 0;
    int catIDSelect = 0;

    /** Creates new form AddCourse */
    public AddCourse() {
        initComponents();
        loadCatComboBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        courseIdOutLbl = new javax.swing.JLabel();
        clrFldsBtn = new javax.swing.JButton();
        catSelectLbl = new javax.swing.JLabel();
        courseNameLbl = new javax.swing.JLabel();
        addCourseBtn = new javax.swing.JButton();
        courseIdLbl = new javax.swing.JLabel();
        courseNameFld = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        catComBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cg41.CG41App.class).getContext().getResourceMap(AddCourse.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        courseIdOutLbl.setText(resourceMap.getString("courseIdOutLbl.text")); // NOI18N
        courseIdOutLbl.setName("courseIdOutLbl"); // NOI18N

        clrFldsBtn.setText(resourceMap.getString("clrFldsBtn.text")); // NOI18N
        clrFldsBtn.setName("clrFldsBtn"); // NOI18N

        catSelectLbl.setText(resourceMap.getString("catSelectLbl.text")); // NOI18N
        catSelectLbl.setName("catSelectLbl"); // NOI18N

        courseNameLbl.setText(resourceMap.getString("courseNameLbl.text")); // NOI18N
        courseNameLbl.setName("courseNameLbl"); // NOI18N

        addCourseBtn.setText(resourceMap.getString("addCourseBtn.text")); // NOI18N
        addCourseBtn.setName("addCourseBtn"); // NOI18N
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        courseIdLbl.setText(resourceMap.getString("courseIdLbl.text")); // NOI18N
        courseIdLbl.setName("courseIdLbl"); // NOI18N

        courseNameFld.setText(resourceMap.getString("courseNameFld.text")); // NOI18N
        courseNameFld.setName("courseNameFld"); // NOI18N

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        catComBox.setName("catComBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseNameLbl)
                    .addComponent(catSelectLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(clrFldsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCourseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(catComBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseNameFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseIdLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseIdOutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(courseNameLbl)
                        .addComponent(courseNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseIdOutLbl))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catSelectLbl)
                    .addComponent(catComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(addCourseBtn)
                    .addComponent(clrFldsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method loads the categories from the database into the combo box
     */
    private void loadCatComboBox() {
        CG41App.dbObject.sqlString = "select COUNT(*) from category";
        thisError = CG41App.dbObject.getCountBySelect(); //count the categories
        numRecords = CG41App.dbObject.NumberOfRecords; //get the amount of categories
        CG41App.dbObject.sqlString = "select CatID, CategoryName from category";
        thisError = CG41App.dbObject.getRecordSetBySelect();//execute query
        if (thisError == 0) {
            try {
                for (i = 0; i < numRecords; i++) {//for the amount of records, add each category
                    CG41App.dbObject.rs.next();
                    //add only the name to the field
                    catComBox.addItem(CG41App.dbObject.rs.getString(2));
                }
            } catch (SQLException ex) {
                // Show errors in console
                System.out.println("SQLException: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("VendorError: " + ex.getErrorCode());
                thisError = ex.getErrorCode();

                UserMessageBox MyMessage = new UserMessageBox();
                MyMessage.setMessage("SQLException: " + ex.getMessage());
                MyMessage.setVisible(true);
            }
        }
    }

    /**
     * This method will, when clicked, add the course and its category to the data base
     */
private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
    myLocalError = false; //set used variables to null
    myLocalString = null;
    thisError = 0;
    numRecords = 0;
    catIDSelect = 0;
    catSelect = "";

    if (courseNameFld.getText().equals("") //check for blank fields
            || catComBox.getSelectedItem().toString().equals("")) {
        myLocalError = true;
        //error for blank fields
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage("Please make sure you have filled out all the fields");
        MyMessage.setTitle("Error Adding Course");
        MyMessage.setVisible(true);
    }
    errorMessage = "Please check the following: \n\n";
    if (!myLocalError) {
        //validation of course name
        if (!CG41App.validateObject.validateCourseName(courseNameFld.getText())) {
            myLocalError = true;
            errorMessage = errorMessage + "The course name should begin with"
                    + "a letter and be followed by up to 20 letters, numbers"
                    + "apostophes, spaces and dashes.";
        }
        if (myLocalError) {
        //One of the validation checks failed
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage(errorMessage);
        MyMessage.setTitle("Error Adding Course");
        MyMessage.setVisible(true);
        }
    }
    //create and set SQL string
    CG41App.dbObject.sqlString = "select COUNT(*) from category";
    thisError = CG41App.dbObject.getCountBySelect();
    numRecords = CG41App.dbObject.NumberOfRecords;
    CG41App.dbObject.sqlString = "select CatID, CategoryName from category";
    thisError = CG41App.dbObject.getRecordSetBySelect(); //execute string

    catSelect = catComBox.getSelectedItem().toString(); //get cat ID from combo box
    for (i = 0; i < numRecords; i++) {
        try {
            CG41App.dbObject.rs.next(); //find the CatID  from the DB search
            if (catSelect.equals(CG41App.dbObject.rs.getString(2))) {
                catIDSelect = CG41App.dbObject.rs.getInt(1);
            }
        } catch (SQLException ex) {
            // Show errors in console
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
            thisError = ex.getErrorCode();

            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setMessage("SQLException: " + ex.getMessage());
            MyMessage.setVisible(true);
        }
    }
    if (!myLocalError) { //add course to the DB
        myLocalString = "insert into course (" + "CatID, CourseName)"
                + "values (" + "'" + catIDSelect + "', "
                + "'" + courseNameFld.getText() + "') "; //concatonate string
        CG41App.dbObject.sqlString = myLocalString; //set string
        thisError = CG41App.dbObject.insertRecord(); //execute

        if (0 == thisError) {
            //if adding is successful
            courseIdOutLbl.setText(Integer.toString(CG41App.dbObject.LastInsertedKey));
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage("Course added successfully");
            MyMessage.setTitle("Adding Course Complete");
            MyMessage.setVisible(true);
        }
        else{
            //if there's an error present
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage("Error Adding Course.");
            MyMessage.setTitle("Error Adding Course");
            MyMessage.setVisible(true);
        }   
    }
}//GEN-LAST:event_addCourseBtnActionPerformed
    /**
     * This method closes the window
     */
private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    dispose();
}//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JComboBox catComBox;
    private javax.swing.JLabel catSelectLbl;
    private javax.swing.JButton clrFldsBtn;
    private javax.swing.JLabel courseIdLbl;
    private javax.swing.JLabel courseIdOutLbl;
    private javax.swing.JTextField courseNameFld;
    private javax.swing.JLabel courseNameLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
