package cg41;

import javax.swing.WindowConstants;

public class AddCategory extends javax.swing.JFrame {

    boolean myLocalError = false;
    String myLocalString, errorMessage = null;
    int thisError = 0;

    /** Creates new form AddGovernor */
    public AddCategory() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        catIdOutLbl = new javax.swing.JLabel();
        clrFldsBtn = new javax.swing.JButton();
        catNameLbl = new javax.swing.JLabel();
        addCatBtn = new javax.swing.JButton();
        catIdLbl = new javax.swing.JLabel();
        catNameFld = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cg41.CG41App.class).getContext().getResourceMap(AddCategory.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        catIdOutLbl.setText(resourceMap.getString("catIdOutLbl.text")); // NOI18N
        catIdOutLbl.setName("catIdOutLbl"); // NOI18N

        clrFldsBtn.setText(resourceMap.getString("clrFldsBtn.text")); // NOI18N
        clrFldsBtn.setName("clrFldsBtn"); // NOI18N
        clrFldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrFldsBtnActionPerformed(evt);
            }
        });

        catNameLbl.setText(resourceMap.getString("catNameLbl.text")); // NOI18N
        catNameLbl.setName("catNameLbl"); // NOI18N

        addCatBtn.setText(resourceMap.getString("addCatBtn.text")); // NOI18N
        addCatBtn.setName("addCatBtn"); // NOI18N
        addCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatBtnActionPerformed(evt);
            }
        });

        catIdLbl.setText(resourceMap.getString("catIdLbl.text")); // NOI18N
        catIdLbl.setName("catIdLbl"); // NOI18N

        catNameFld.setText(resourceMap.getString("catNameFld.text")); // NOI18N
        catNameFld.setName("catNameFld"); // NOI18N

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(catNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(catNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(catIdLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catIdOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(clrFldsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catNameLbl)
                        .addComponent(catNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catIdOutLbl))
                        .addGap(5, 5, 5)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(addCatBtn)
                    .addComponent(clrFldsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void addCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatBtnActionPerformed
    myLocalError = false; //set variables used to null
    thisError = 0;
    myLocalString = "";
    if ((catNameFld.getText().equals(""))) {//check for blank field
        myLocalError = true;
    }
    if (myLocalError) {
        // field must be blank, so error
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage("Please Enter a Name for the Category.");
        MyMessage.setTitle("Error Adding Category");
        MyMessage.setVisible(true);
    }
    errorMessage = "Please check the following: \n\n";
    if (!myLocalError) { //if there's no error
        //validate category name
        if (!CG41App.validateObject.validateCategoryName(catNameFld.getText())) {
            myLocalError = true; //set error true and add to the error message
            errorMessage = errorMessage + "Category name should be no longer than 22 characters and"
                    + "must begin with a letter, space, dash or apostrophe.";
        }
        if (myLocalError) {
            //One of the validation checks failed
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage(errorMessage);
            MyMessage.setTitle("Error Adding Category");
            MyMessage.setVisible(true);
        }
    }
    if (!myLocalError) { //add in the database
        myLocalString = "insert into category (" + "CategoryName)" + "values (";
        myLocalString = myLocalString + "'" + catNameFld.getText() + "') ";
        CG41App.dbObject.sqlString = myLocalString; //set the SQL string
        thisError = CG41App.dbObject.insertRecord(); //execute string

        if (0 == thisError) {
            //adding was successful
            catIdOutLbl.setText(Integer.toString(CG41App.dbObject.LastInsertedKey));
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage("Category Added Edited.");
            MyMessage.setTitle("Category Edited");
        }
    }

}//GEN-LAST:event_addCatBtnActionPerformed
    /**
     * This method closes the window
     */
private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    dispose();
}//GEN-LAST:event_exitBtnActionPerformed
    /**
     * this method clears the category field for more input
     */
private void clrFldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrFldsBtnActionPerformed
    catNameFld.setText("");
}//GEN-LAST:event_clrFldsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddCategory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCatBtn;
    private javax.swing.JLabel catIdLbl;
    private javax.swing.JLabel catIdOutLbl;
    private javax.swing.JTextField catNameFld;
    private javax.swing.JLabel catNameLbl;
    private javax.swing.JButton clrFldsBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
