package cg41;

import java.util.Date;
import javax.swing.WindowConstants;

public class AddGovernor extends javax.swing.JFrame {

    boolean myLocalError = false;
    String endDateString, elecDateString, myLocalString, errorMessage = "";
    int thisError = 0;
    Date endDate, elecDate;

    /** Creates new form AddGovernor */
    public AddGovernor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        govIdOutLbl = new javax.swing.JLabel();
        endDateLbl = new javax.swing.JLabel();
        clrFldsBtn = new javax.swing.JButton();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        lstNamLbl = new javax.swing.JLabel();
        frstNamLbl = new javax.swing.JLabel();
        elecDateChooser = new com.toedter.calendar.JDateChooser();
        addGovBtn = new javax.swing.JButton();
        govIdLbl = new javax.swing.JLabel();
        lstNamFld = new javax.swing.JTextField();
        frstNamFld = new javax.swing.JTextField();
        elecDateLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cg41.CG41App.class).getContext().getResourceMap(AddGovernor.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        govIdOutLbl.setText(resourceMap.getString("govIdOutLbl.text")); // NOI18N
        govIdOutLbl.setName("govIdOutLbl"); // NOI18N

        endDateLbl.setText(resourceMap.getString("endDateLbl.text")); // NOI18N
        endDateLbl.setName("endDateLbl"); // NOI18N

        clrFldsBtn.setText(resourceMap.getString("clrFldsBtn.text")); // NOI18N
        clrFldsBtn.setName("clrFldsBtn"); // NOI18N
        clrFldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrFldsBtnActionPerformed(evt);
            }
        });

        endDateChooser.setName("endDateChooser"); // NOI18N

        lstNamLbl.setText(resourceMap.getString("lstNamLbl.text")); // NOI18N
        lstNamLbl.setName("lstNamLbl"); // NOI18N

        frstNamLbl.setText(resourceMap.getString("frstNamLbl.text")); // NOI18N
        frstNamLbl.setName("frstNamLbl"); // NOI18N

        elecDateChooser.setName("elecDateChooser"); // NOI18N

        addGovBtn.setText(resourceMap.getString("addGovBtn.text")); // NOI18N
        addGovBtn.setName("addGovBtn"); // NOI18N
        addGovBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGovBtnActionPerformed(evt);
            }
        });

        govIdLbl.setText(resourceMap.getString("govIdLbl.text")); // NOI18N
        govIdLbl.setName("govIdLbl"); // NOI18N

        lstNamFld.setText(resourceMap.getString("lstNamFld.text")); // NOI18N
        lstNamFld.setName("lstNamFld"); // NOI18N

        frstNamFld.setText(resourceMap.getString("frstNamFld.text")); // NOI18N
        frstNamFld.setName("frstNamFld"); // NOI18N

        elecDateLbl.setText(resourceMap.getString("elecDateLbl.text")); // NOI18N
        elecDateLbl.setName("elecDateLbl"); // NOI18N

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elecDateLbl)
                    .addComponent(frstNamLbl)
                    .addComponent(lstNamLbl)
                    .addComponent(endDateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(clrFldsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(addGovBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn))
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(frstNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(govIdLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(govIdOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(lstNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elecDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frstNamLbl)
                        .addComponent(frstNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(govIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(govIdOutLbl))
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstNamLbl)
                    .addComponent(lstNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elecDateLbl)
                    .addComponent(elecDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateLbl)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(addGovBtn)
                    .addComponent(clrFldsBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * This method is used to add a governor on click of the add governor button
     */
private void addGovBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGovBtnActionPerformed
    myLocalError = false; //set used variables to empty
    thisError = 0;
    myLocalString = "";

    elecDate = elecDateChooser.getDate(); //convert date strings to Dates variables
    elecDateString = String.format("%1$tY-%1$tm-%1$td", elecDate); //format dates
    endDate = endDateChooser.getDate();
    endDateString = String.format("%1$tY-%1$tm-%1$td", endDate);

    //Quick check to see if the fields have been filled in, else print an error
    if (frstNamFld.getText().equals("") 
            || lstNamFld.getText().equals("")
            || elecDateString.equals("null-null-null")
            || endDateString.equals("null-null-null")) {
        myLocalError = true;
    }
    if (myLocalError) {
        // One field must be blank, therefore display an error
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage("Please Fill Out All Fields.");
        MyMessage.setTitle("Error Adding Governor");
        MyMessage.setVisible(true);
    }
    //Error checking for validation of each field where an error message will be
    //created for the user's viewing for any errors
    errorMessage = "Please check the following: \n\n";
    if (!myLocalError) { 
        //validation of first name
        if(!CG41App.validateObject.validateFirstName(frstNamFld.getText())){
            myLocalError = true;
            errorMessage = errorMessage + "First name should begin with a capital"
                    + " and be no longer than 10 characters. \n\n";
        }
        //validation of last name
        if(!CG41App.validateObject.validateSurname(lstNamFld.getText())){
            myLocalError = true; 
            errorMessage = errorMessage + "Last name should begin with a letter"
                    + " and be no longer than 20 characters and can include"
                    + " spaces, dashes and apostrophes. \n\n";
        }
        //check to see if the election date is after the end date
        if (elecDate.after(endDate)) {
            myLocalError = true;
            errorMessage = errorMessage + "Make sure the elected date is before"
                    + " the 'end date'.";
        }
         //DB check
        if (!myLocalError) {
        // TODO Check if already in database
        }
        if (myLocalError) {
        //One of the validation checks failed
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage(errorMessage);
        MyMessage.setTitle("Error Adding Governor");
        MyMessage.setVisible(true);
        }
    }    
    if (!myLocalError) { //add the governor to the DB
        myLocalString = "insert into governor (";
        myLocalString = myLocalString + "Firstname, Surname, ElectionDate, EndDate)"
                + " values ("
                + "'" + frstNamFld.getText() + "', "
                + "'" + lstNamFld.getText() + "', "
                + "'" + elecDateString + "', "
                + "'" + endDateString + "') ";
        CG41App.dbObject.sqlString = myLocalString; //set MySQL string
        thisError = CG41App.dbObject.insertRecord(); //execute MySQL string

        if (0 == thisError) { //set the new governor ID so the user can see it
            govIdOutLbl.setText(Integer.toString(CG41App.dbObject.LastInsertedKey));
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage("Governor Added Successfuly.");
            MyMessage.setTitle("Governor Added");
            MyMessage.setVisible(true);
        }
    }
}//GEN-LAST:event_addGovBtnActionPerformed

/**
 * This method closes the window 
 */
private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    dispose();
}//GEN-LAST:event_exitBtnActionPerformed

/**
 * This method clears all the fields so the user can add another governor
 */
private void clrFldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrFldsBtnActionPerformed
    frstNamFld.setText("");
    lstNamFld.setText(""); 
    elecDateChooser.setDate(null);
    endDateChooser.setDate(null);
    govIdOutLbl.setText("-");
}//GEN-LAST:event_clrFldsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGovernor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGovernor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGovernor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGovernor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddGovernor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGovBtn;
    private javax.swing.JButton clrFldsBtn;
    private com.toedter.calendar.JDateChooser elecDateChooser;
    private javax.swing.JLabel elecDateLbl;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JLabel endDateLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField frstNamFld;
    private javax.swing.JLabel frstNamLbl;
    private javax.swing.JLabel govIdLbl;
    private javax.swing.JLabel govIdOutLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lstNamFld;
    private javax.swing.JLabel lstNamLbl;
    // End of variables declaration//GEN-END:variables
}
