package cg41;

import java.sql.SQLException;
import javax.swing.WindowConstants;

public class EditCategory extends javax.swing.JFrame {

    boolean myLocalError = false;
    String myLocalString = null;
    String category, myCat, errorMessage = "";
    String myCatArray[];
    int thisError, i, numRecords = 0;

    /** Creates new form AddGovernor */
    public EditCategory() {
        initComponents();
        loadCategories();
    }

    /**
     * This method loads the categories from the database into a combo box
     */
    private void loadCategories() {
        //create and execute the SQL string to get num of records and get the RecordSet
        CG41App.dbObject.sqlString = "select COUNT(*) from category";
        thisError = CG41App.dbObject.getCountBySelect();
        numRecords = CG41App.dbObject.NumberOfRecords;
        CG41App.dbObject.sqlString = "select CatID, CategoryName from category";
        thisError = CG41App.dbObject.getRecordSetBySelect();
        if (thisError == 0) {
            try {
                for (i = 0; i < numRecords; i++) {
                    //for each item in the RS, add the category
                    CG41App.dbObject.rs.next();
                    category = CG41App.dbObject.rs.getString(1) + ", "
                            + CG41App.dbObject.rs.getString(2);
                    catCombox.addItem(category);
                }
            } catch (SQLException ex) {
                // Show errors in console
                System.out.println("SQLException: " + ex.getMessage());
                System.out.println("SQLState: " + ex.getSQLState());
                System.out.println("VendorError: " + ex.getErrorCode());
                thisError = ex.getErrorCode();

                UserMessageBox MyMessage = new UserMessageBox();
                MyMessage.setMessage("SQLException: " + ex.getMessage());
                MyMessage.setVisible(true);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        catIDOutLbl = new javax.swing.JLabel();
        loadCatBtn = new javax.swing.JButton();
        catNameLbl = new javax.swing.JLabel();
        editCatBtn = new javax.swing.JButton();
        catIdLbl = new javax.swing.JLabel();
        catNamFld = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        catCombox = new javax.swing.JComboBox();
        catLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cg41.CG41App.class).getContext().getResourceMap(EditCategory.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        catIDOutLbl.setText(resourceMap.getString("catIDOutLbl.text")); // NOI18N
        catIDOutLbl.setName("catIDOutLbl"); // NOI18N

        loadCatBtn.setText(resourceMap.getString("loadCatBtn.text")); // NOI18N
        loadCatBtn.setName("loadCatBtn"); // NOI18N
        loadCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCatBtnActionPerformed(evt);
            }
        });

        catNameLbl.setText(resourceMap.getString("catNameLbl.text")); // NOI18N
        catNameLbl.setName("catNameLbl"); // NOI18N

        editCatBtn.setText(resourceMap.getString("editCatBtn.text")); // NOI18N
        editCatBtn.setName("editCatBtn"); // NOI18N
        editCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCatBtnActionPerformed(evt);
            }
        });

        catIdLbl.setText(resourceMap.getString("catIdLbl.text")); // NOI18N
        catIdLbl.setName("catIdLbl"); // NOI18N

        catNamFld.setText(resourceMap.getString("catNamFld.text")); // NOI18N
        catNamFld.setName("catNamFld"); // NOI18N

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        catCombox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        catCombox.setName("catCombox"); // NOI18N

        catLbl.setText(resourceMap.getString("catLbl.text")); // NOI18N
        catLbl.setName("catLbl"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catNameLbl)
                            .addComponent(catLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(catCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loadCatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(catNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(catIdLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catIDOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(editCatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catLbl)
                    .addComponent(loadCatBtn)
                    .addComponent(catCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catNameLbl)
                        .addComponent(catNamFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catIDOutLbl))
                        .addGap(5, 5, 5)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(editCatBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * This method waits for the user to press the edit button and then amends the
 * category in the database with the edited version
 */
private void editCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCatBtnActionPerformed
    myLocalError = false; //set all variables to null
    thisError = 0;
    myLocalString = "";

    // Check if all fields are filled in.  If not, then print an error
    // message and don't do any more processing
    if (catNamFld.getText().equals("")) {
        myLocalError = true;

        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        MyMessage.setMessage("Please Enter All Fields.");
        MyMessage.setTitle("Error Editing Category");
        MyMessage.setVisible(true);
    }
    errorMessage = "Please check the following: \n\n";
    if (!myLocalError) {
        if(!CG41App.validateObject.validateCategoryName(catNamFld.getText())){
            myLocalError = true;
            errorMessage = errorMessage + "Category name should begin with a letter"
                    + " and be no longer than 20 characters and can include"
                    + " spaces, dashes and apostrophes. \n\n";
        }
    }
    if (!myLocalError) {
        // TODO Check if already in database
    }
    if (!myLocalError) {
        myLocalString = "update category set "
                + "CategoryName=" + "'" + catNamFld.getText().toString() + "'"
                + " where CatID= " + catIDOutLbl.getText();
        CG41App.dbObject.sqlString = myLocalString;
        thisError = CG41App.dbObject.updateRecord();
    }
    if (0 == thisError) { //set the new governor ID so the user can see it
            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            MyMessage.setMessage("Category was successfully edited.");
            MyMessage.setTitle("Category Edited Successfully");
            MyMessage.setVisible(true);
        }
}//GEN-LAST:event_editCatBtnActionPerformed

/**
 * This method closes the window
 */
private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    dispose();
}//GEN-LAST:event_exitBtnActionPerformed
/**
 * This method loads the selected category from the combo box into the fields
 * for editing
 */
private void loadCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCatBtnActionPerformed
    myLocalString = ""; //reset variables
    myCat = "";
    thisError = 0;
    
    myCat = catCombox.getSelectedItem().toString(); //get category string
    myCatArray = myCat.split(","); //split it to make it handlable 
    myLocalString = "select * from category where CatID = '"
            + myCatArray[0] + "'"; //select the category where the IDs match
    CG41App.dbObject.sqlString = myLocalString; //set the SQL string
    thisError = CG41App.dbObject.getRecordSetBySelect(); //execute the query
    try {
        CG41App.dbObject.rs.next();
        //output the category name for editing as well as the category ID for later
        catNamFld.setText(CG41App.dbObject.rs.getString("CategoryName"));
        catIDOutLbl.setText((myCatArray[0])); 
    } catch (SQLException ex) {
        // Show errors in console
        System.out.println("SQLException: " + ex.getMessage());
        System.out.println("SQLState: " + ex.getSQLState());
        System.out.println("VendorError: " + ex.getErrorCode());
        thisError = ex.getErrorCode();
        UserMessageBox MyMessage = new UserMessageBox();
        MyMessage.setMessage("SQLException: " + ex.getMessage());
        MyMessage.setVisible(true);
    }
}//GEN-LAST:event_loadCatBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditCategory().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox catCombox;
    private javax.swing.JLabel catIDOutLbl;
    private javax.swing.JLabel catIdLbl;
    private javax.swing.JLabel catLbl;
    private javax.swing.JTextField catNamFld;
    private javax.swing.JLabel catNameLbl;
    private javax.swing.JButton editCatBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadCatBtn;
    // End of variables declaration//GEN-END:variables
}
