package cg41;

import java.sql.SQLException;
import java.util.Date;
import javax.swing.JTable;

public class ViewGovernors extends javax.swing.JFrame {

    String govID, firstname, surname;
    Date elecDate, endDate;
    int thisError, numRecords = 0;

    public ViewGovernors() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        governorScrlPane = new javax.swing.JScrollPane();
        governorTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cg41.CG41App.class).getContext().getResourceMap(ViewGovernors.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        refreshBtn.setText(resourceMap.getString("refreshBtn.text")); // NOI18N
        refreshBtn.setName("refreshBtn"); // NOI18N
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        governorScrlPane.setName("governorScrlPane"); // NOI18N

        governorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Governor ID", "First Name", "Last Name", "Elected Date", "End Date"
            }
        ));
        governorTbl.setName("governorTbl"); // NOI18N
        governorScrlPane.setViewportView(governorTbl);
        governorTbl.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("governorTbl.columnModel.title0")); // NOI18N
        governorTbl.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("governorTbl.columnModel.title1")); // NOI18N
        governorTbl.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("governorTbl.columnModel.title2")); // NOI18N
        governorTbl.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("governorTbl.columnModel.title3")); // NOI18N
        governorTbl.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("governorTbl.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn))
                    .addComponent(governorScrlPane))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(governorScrlPane, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(refreshBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is used to close the window when the exit button is pressed
     */
private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    dispose();
}//GEN-LAST:event_exitBtnActionPerformed
/**
 * this method refreshes the table for when governors have been added, edited
 * or removed elsewhere
 */
private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
    //set select statement
    CG41App.dbObject.sqlString = "select COUNT(*) from governor";
    thisError = CG41App.dbObject.getCountBySelect(); //execute count by select

    numRecords = CG41App.dbObject.NumberOfRecords; //save number of records

    // Construct an SQL statment to find all governors
    CG41App.dbObject.sqlString =
            "select GovID, Firstname, "
            + "Surname, ElectionDate, EndDate from governor";
    // Execute the query
    thisError = CG41App.dbObject.getRecordSetBySelect();
    if (thisError == 0) {
        // No error on execution of statement
        // In order to make a table, you need to create an array of objects
        // It must be as long as the number of records you've counted and
        // must be as wide as the number of columns you've asked for
        Object[][] myTableData = new Object[numRecords][5];
        String[] myColumnNames = {"Governor ID", "First Name", "Surname",
            "Elected Date", "End Date"};
        try {
            int row = 0;
            while (CG41App.dbObject.rs.next()) // For each record
            {
                //get each part of the governor from the Record Set
                govID = CG41App.dbObject.rs.getString("GovID");
                firstname = CG41App.dbObject.rs.getString("Firstname");
                surname = CG41App.dbObject.rs.getString("Surname");
                elecDate = CG41App.dbObject.rs.getDate("ElectionDate");
                endDate = CG41App.dbObject.rs.getDate("EndDate");
                myTableData[row][0] = govID;
                myTableData[row][1] = firstname;
                myTableData[row][2] = surname;
                myTableData[row][3] = String.valueOf(elecDate);
                myTableData[row][4] = String.valueOf(endDate);
                row = row + 1;           // Next row in table
            }

            // Have the table data, so make a new table with it
            JTable jtblAllGovernors = new JTable(myTableData, myColumnNames);
            jtblAllGovernors.setFillsViewportHeight(true);
            governorScrlPane.getViewport().add(jtblAllGovernors);
            governorScrlPane.repaint();
        } catch (SQLException ex) {
            // Show errors in console
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
            thisError = ex.getErrorCode();

            UserMessageBox MyMessage = new UserMessageBox();
            MyMessage.setMessage("SQLException: " + ex.getMessage());
            MyMessage.setVisible(true);
        }
    }
}//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGovernors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGovernors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGovernors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGovernors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewGovernors().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane governorScrlPane;
    private javax.swing.JTable governorTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
